name: test

permissions: {}

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, labeled]
  push:
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version-file: .dvmrc
      - uses: actions/setup-node@v2
      - name: Build
        run: |
          deno lint
          npm ci
          npm run build
